#### We will perform the matrix multiplication in the exponential contained in the normal pdf
\begin{equation}
p(\textbf{x};\mu,\Sigma)= \frac{1}{(2\pi)^{n/2}|\Gamma^{-1}|^{1/2}} \mathrm{exp} \Big[-\frac{1}{2}(\textbf{x}-\mu)^{T}\Gamma(\textbf{x}-\mu)\Big].
\end{equation}

#### where 
\begin{equation}
\textbf{x}=(m_1,m_2)
\end{equation}

#### and 
\begin{equation}
\mu=\big(E[m_1], E[m_2]\big)
\end{equation}


In [1]:
cd V4m1m2

/home/josecarlos/Desktop/Jose/Fisher/GWFish/LISA/V4m1m2


In [3]:
import numpy as np

#### We load the files which contains the Fisher matrices and the true values of $m_1$ and $m_2$.

In [4]:
path = '/home/josecarlos/Desktop/Jose/Fisher/GWFish/LISA/V4m1m2/'

fisherfile = 'Fishers_LISA_150914_randompopulationV4m1m2_SNR0.0.npy'
invfisherfile = 'Inv_Fishers_LISA_150914_randompopulationV4m1m2_SNR0.0.npy'

fisher = np.load(path+fisherfile)
invfisher = np.load(path+invfisherfile)

In [5]:
data = np.loadtxt(fname='Errors_LISA_150914_randompopulationV4m1m2a_SNR0.0.txt', delimiter=' ')
print(data)

[[4.94229032e+04 3.78100000e+05 4.93500000e+05 ... 1.18700000e+09
  8.92600000e+00 1.09300000e+01]
 [2.23521114e+04 1.37100000e+05 1.93400000e+05 ... 1.18700000e+09
  2.03100000e+00 2.91200000e+00]
 [5.36074593e+04 4.78700000e+05 4.64400000e+05 ... 1.18700000e+09
  1.26500000e+01 1.24100000e+01]
 ...
 [3.66799201e+04 3.72900000e+05 2.52200000e+05 ... 1.18700000e+09
  5.77800000e+00 4.07600000e+00]
 [3.52851759e+04 2.68800000e+05 3.05300000e+05 ... 1.18700000e+09
  8.64800000e+00 9.71000000e+00]
 [4.55020273e+04 4.93400000e+05 3.22100000e+05 ... 1.18700000e+09
  3.70700000e+00 2.67000000e+00]]


#### We arrange the true values $E[m_1]$ and $E[m_2]$ for only one event  in $\mu$, which is a 2x1 matrix. Later on we will consider the whole population of 300 events.

In [21]:
truevaluem1 = data[0, 1]
truevaluem2 = data[0, 2]
print(truevaluem1)
print(truevaluem2)

378100.0
493500.0


In [23]:
mu =np.array([[truevaluem1], [truevaluem2]])
print(mu)

[[378100.]
 [493500.]]


#### Here we generate the uniform grid $(m_1,m_2)$ in which we will evaluate our pdf. The mass range is $1\times10⁵$ - $5\times10⁵$ in a grid of 9 points as a test.

In [9]:
m1axis = np.linspace(100000, 500000, 3)
m2axis = np.linspace(100000, 500000, 3)

# full coordinate arrays
m1grid, m2grid = np.meshgrid(m1axis, m2axis)

In [10]:
print(m1grid)

[[100000. 300000. 500000.]
 [100000. 300000. 500000.]
 [100000. 300000. 500000.]]


In [11]:
print(m2grid)

[[100000. 100000. 100000.]
 [300000. 300000. 300000.]
 [500000. 500000. 500000.]]


#### We perform the subtractions $m_1 - E(m_1)$ and $m_2 - E(m_2)$ and store them in the 2x1 matrix $(\textbf{x}-\mu)$ and compute $(\textbf{x}-\mu)^{T}$

In [12]:
x_mu1 =np.subtract(m1grid, mu[0])
x_mu2 =np.subtract(m2grid, mu[1])

In [13]:
print(x_mu1)

[[-278100.  -78100.  121900.]
 [-278100.  -78100.  121900.]
 [-278100.  -78100.  121900.]]


In [14]:
print(x_mu2)

[[-393500. -393500. -393500.]
 [-193500. -193500. -193500.]
 [   6500.    6500.    6500.]]


In [15]:
x_mu = np.array([x_mu1,x_mu2])
x_muT = np.transpose(x_mu)

In [16]:
print(x_mu)

[[[-278100.  -78100.  121900.]
  [-278100.  -78100.  121900.]
  [-278100.  -78100.  121900.]]

 [[-393500. -393500. -393500.]
  [-193500. -193500. -193500.]
  [   6500.    6500.    6500.]]]


In [18]:
print(x_muT)

[[[-278100. -393500.]
  [-278100. -193500.]
  [-278100.    6500.]]

 [[ -78100. -393500.]
  [ -78100. -193500.]
  [ -78100.    6500.]]

 [[ 121900. -393500.]
  [ 121900. -193500.]
  [ 121900.    6500.]]]


#### We perform the matrix multiplication $(\textbf{x}-\mu)^{T}\Gamma$ 

In [19]:
exp1 = np.matmul(x_muT, fisher[0])
print(exp1.shape)
print(exp1)

(3, 3, 2)
[[[-61702954.00327376 -50395389.2977656 ]
  [-44890652.39267815 -36663300.9073044 ]
  [-28078350.78208254 -22931212.5168432 ]]

 [[-41117013.27373265 -33583087.68717   ]
  [-24304711.66313705 -19850999.29670879]
  [ -7492410.05254144  -6118910.90624759]]

 [[-20531072.54419155 -16770786.07657439]
  [ -3718770.93359595  -3038697.68611319]
  [ 13093530.67699966  10693390.70434801]]]


#### and the result from above by $(\textbf{x} - \mu)$

In [24]:
exp = np.matmul(exp1, x_mu)
print(exp.shape)
print(exp)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)